global:
  database:
    host: "docker.bnh.vn"
    port: 5432
    user: vvp
    password: "oracle_4U"
    provider: postgresql
    createIfMissing: false

  rbac:
    additionalNamespaces:
      - vvp-deploy

  authentication:
    single-user:
      enabled: true

  image:
    registry: "registry.bnh.vn/registry.ververica.cloud"

  imagePullSecretName: registry-common

  blobStorage:
    baseUri: "s3i://vvp"
    s3:
      endpoint: "http://docker.bnh.vn:9000"
      accessKeyId: "admin"
      secretAccessKey: "oracle_4U"

  vvp:
    license:
      data: {}

api-gateway:
  publicApiEndpoint: "http://vvp.apps.k8s.bnh.vn"

vvp-gateway:
  resources:
    limits:
      cpu: "1"
      memory: "3.5Gi"
    requests:
      cpu: "0.25"
      memory: "1Gi"

vvp-appmanager:
  flinkVersionMetas:
    jdk11:
      installByDefault: false
    jdk17:
      installByDefault: true

  resources:
    limits:
      cpu: "1"
      memory: "3.5Gi"
    requests:
      cpu: "0.5"
      memory: "3Gi"

  globalDeploymentDefaults:
    numberOfTaskSlots: 1
    flinkConfiguration:
      execution.checkpointing.interval: "10s"
      web.cancel.enable: "false"
    spec:
      template:
        spec:
          kubernetes:
            pods:
              nodeSelector:
                workload.ververica.io/pool: lab

  globalSessionClusterDefaults: |-
    spec:
      flinkConfiguration:
        taskmanager.numberOfTaskSlots: "1"
        web.cancel.enable: "false"
      kubernetes:
        pods:
          nodeSelector:
            workload.ververica.io/pool: lab

vvp-appagent:
  persistentVolume:
    size: 40Gi
    storageClass: vsphere-rwo

  appAgentResources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "0.25"
      memory: "1Gi"

  sqlServiceResources:
    limits:
      cpu: "1"
      memory: "3.5Gi"
    requests:
      cpu: "0.5"
      memory: "2.5Gi"

vvp-autopilot:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "0.25"
      memory: "1Gi"

vvp-meta:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "0.25"
      memory: "1Gi"

vvp-advisor:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "0.25"
      memory: "1Gi"

vvp-console-ui:
  ui:
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
