apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vvp
  namespace: vvp-system
spec:
  host: vvp.apps.ocp.bnh.vn
  to:
    kind: Service
    name: api-gateway
  port:
    targetPort: http-alt
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
